export const FETCH_TUTORIALS = 'FETCH_TUTORIALS';
export const FETCH_TUTORIALS_SUCCESS = 'FETCH_TUTORIALS_SUCCESS';
export const FETCH_TUTORIALS_ERROR = 'FETCH_TUTORIALS_ERROR';

export const REMOVE_ALL_TUTORIALS = 'REMOVE_ALL_TUTORIALS';
export const REMOVE_ALL_TUTORIALS_SUCCESS = 'REMOVE_ALL_TUTORIALS_SUCCESS';
export const REMOVE_ALL_TUTORIALS_ERROR = 'REMOVE_ALL_TUTORIALS_ERROR';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';

export const CREATE_TUTORIALS = 'CREATE_TUTORIALS';
export const CREATE_TUTORIALS_SUCCESS = 'CREATE_TUTORIALS_SUCCESS';
export const CREATE_TUTORIALS_ERROR = 'CREATE_TUTORIALS_ERROR';

export const EDIT_TUTORIAL = 'EDIT_TUTORIAL';
export const EDIT_TUTORIAL_SUCCESS = 'EDIT_TUTORIAL_SUCCESS';
export const EDIT_TUTORIAL_ERROR = 'EDIT_TUTORIAL_ERROR';

export const DELETE_TUTORIAL = 'DELETE_TUTORIAL';
export const DELETE_TUTORIAL_SUCCESS = 'DELETE_TUTORIAL_SUCCESS';
export const DELETE_TUTORIAL_ERROR = 'DELETE_TUTORIAL_ERROR';

export const FETCH_TUTORIAL = 'FETCH_TUTORIAL';
export const FETCH_TUTORIAL_SUCCESS = 'FETCH_TUTORIAL_SUCCESS';
export const FETCH_TUTORIAL_ERROR = 'FETCH_TUTORIAL_ERROR';

export const FIND_TUTORIALS = 'FIND_TUTORIALS';
export const FIND_TUTORIALS_SUCCESS = 'FIND_TUTORIALS_SUCCESS';
export const FIND_TUTORIALS_ERROR = 'FIND_TUTORIALS_ERROR';
